<?xml version="1.0" encoding="UTF-8"?>
<project version="4">
  <component name="DataSourceManagerImpl" format="xml" multifile-model="true">
    <data-source source="LOCAL" name="db" uuid="01c53989-a4a2-4f36-8ae1-e02b06899203">
      <driver-ref>sqlite.xerial</driver-ref>
      <synchronize>true</synchronize>
      <jdbc-driver>org.sqlite.JDBC</jdbc-driver>
      <jdbc-url>jdbc:sqlite:D:\Applications\PyCharm 2019.3.4\Django\db.sqlite3</jdbc-url>
    </data-source>
    <data-source source="LOCAL" name="db [2]" uuid="d1fa064c-2b7f-4439-8d29-8647c1a092f4">
      <driver-ref>sqlite.xerial</driver-ref>
      <synchronize>true</synchronize>
      <jdbc-driver>org.sqlite.JDBC</jdbc-driver>
      <jdbc-url>jdbc:sqlite:C:\Users\Jiyoon\Dropbox\Hyeongseop_Jiyoon\Django\db.sqlite3</jdbc-url>
    </data-source>
    <data-source source="LOCAL" name="SQLite - identifier.sqlite" uuid="0353dc46-7e31-429a-9187-41a3684a48d0">
      <driver-ref>sqlite.xerial</driver-ref>
      <synchronize>true</synchronize>
      <jdbc-driver>org.sqlite.JDBC</jdbc-driver>
      <jdbc-url>jdbc:sqlite:identifier.sqlite</jdbc-url>
    </data-source>
  </component>
</project>